In [1]:
import platform
platform.platform()

'macOS-15.6.1-arm64-arm-64bit'

In [2]:
import sys
sys.version

'3.10.19 | packaged by conda-forge | (main, Oct 22 2025, 22:46:49) [Clang 19.1.7 ]'

In [3]:
import mordred
mordred.__version__

'1.2.0'

In [4]:
from mordred import Calculator, descriptors

In [5]:
import numpy as np
np.__version__

'1.23.5'

In [6]:
import pandas as pd
pd.__version__

'2.3.3'

In [7]:
from rdkit import Chem, rdBase
rdBase.rdkitVersion

'2023.09.1'

In [8]:
df1 = pd.read_csv("../1_28descriptors/1_dataset/1_original/dataset.csv",
                  usecols=["SMILES", "InChI", "InChIKey", "K3FeCN6"])
df1.shape

(4665, 4)

In [9]:
df1.columns

Index(['SMILES', 'InChI', 'InChIKey', 'K3FeCN6'], dtype='object')

In [10]:
df1.drop(df1[df1["K3FeCN6"] == 0].index, inplace=True)
df1.shape

(74, 4)

In [11]:
df1["K3FeCN6"].value_counts()

K3FeCN6
-1    51
 1    23
Name: count, dtype: int64

In [12]:
df1["ROMol"] = df1["InChI"].map(Chem.MolFromInchi)
df1.shape

(74, 5)

In [13]:
calc = Calculator(descriptors, ignore_3D=True)
df_mordred = calc.pandas(df1.loc[:, "ROMol"])

100%|██████████| 74/74 [00:01<00:00, 45.31it/s]

In [14]:
df_mordred.shape

(74, 1613)

In [15]:
df_mordred.columns

Index(['ABC', 'ABCGG', 'nAcid', 'nBase', 'SpAbs_A', 'SpMax_A', 'SpDiam_A',
       'SpAD_A', 'SpMAD_A', 'LogEE_A',
       ...
       'SRW10', 'TSRW10', 'MW', 'AMW', 'WPath', 'WPol', 'Zagreb1', 'Zagreb2',
       'mZagreb1', 'mZagreb2'],
      dtype='object', length=1613)

In [16]:
df2 = df_mordred.select_dtypes(include="number")
df2

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,11.505844,10.846846,0,0,16.340176,2.416610,4.833220,16.340176,1.089345,3.615869,...,9.745136,47.504739,206.167065,5.572083,342,22,78.0,88.0,8.208333,3.027778
1,8.554231,8.109401,0,0,14.962536,2.287941,4.575881,14.962536,1.246878,3.368832,...,9.038959,42.028335,164.083730,6.836822,204,15,54.0,60.0,4.833333,2.944444
3,6.473351,6.127583,0,0,11.189957,2.193993,4.387987,11.189957,1.243329,3.089765,...,8.590258,37.289972,124.052429,7.297202,90,9,40.0,43.0,3.472222,2.166667
5,9.676484,9.250172,0,0,15.001092,2.375265,4.750531,15.001092,1.153930,3.464937,...,9.449908,44.334127,180.115030,6.210863,234,18,64.0,72.0,6.395833,2.861111
10,7.249407,6.999636,0,0,12.376804,2.268236,4.536472,12.376804,1.237680,3.197666,...,8.913416,39.312189,138.068080,6.903404,115,12,46.0,51.0,4.333333,2.361111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3875,8.302711,7.854212,0,0,12.507813,2.317687,4.635374,12.507813,1.137074,3.302531,...,9.193499,41.341650,150.104465,6.004179,148,13,54.0,59.0,5.284722,2.333333
3876,8.732571,8.385662,0,0,14.410869,2.316847,4.633693,14.410869,1.200906,3.376150,...,9.166911,42.386933,166.062994,7.548318,193,16,56.0,63.0,5.444444,2.805556
3878,11.411168,9.996080,0,0,19.589763,2.345288,4.690577,19.589763,1.305984,3.627511,...,9.458216,46.802797,198.068080,7.922723,362,21,74.0,85.0,4.694444,3.416667
3889,7.887564,7.185473,0,0,13.725227,2.205946,4.411892,13.725227,1.247748,3.278326,...,8.696677,40.025593,152.083730,6.612336,174,11,48.0,51.0,3.972222,2.666667
3890,7.847124,7.585047,0,0,13.665822,2.283101,4.566202,13.665822,1.242347,3.287086,...,8.997518,40.726374,154.062994,7.336333,154,14,50.0,56.0,4.583333,2.694444

In [17]:
df2.shape

(74, 1332)

In [18]:
df_error = df_mordred.select_dtypes(exclude="number")
df_error

,AATS7dv,AATS8dv,AATS7d,AATS8d,AATS7s,AATS8s,AATS7Z,AATS8Z,AATS7m,AATS8m,...,MDEC-44,MDEO-11,MDEO-12,MDEO-22,MDEN-11,MDEN-12,MDEN-13,MDEN-22,MDEN-23,MDEN-33
0,0.0,0.0,1.0,1.0,2.36,1.0,5.64,1.0,11.258554,1.016064,...,0.25,float division by zero (MDEO-11),float division by zero (MDEO-12),float division by zero (MDEO-22),float division by zero (MDEN-11),float division by zero (MDEN-12),float division by zero (MDEN-13),float division by zero (MDEN-22),float division by zero (MDEN-23),float division by zero (MDEN-33)
1,0.48,0.0,1.4,1.0,2.533333,2.666667,6.52,4.666667,19.310701,9.080064,...,float division by zero (MDEC-44),float division by zero (MDEO-11),0.333333,float division by zero (MDEO-22),float division by zero (MDEN-11),float division by zero (MDEN-12),float division by zero (MDEN-13),float division by zero (MDEN-22),float division by zero (MDEN-23),float division by zero (MDEN-33)
3,0.0,0.0,1.0,1.0,5.0,1.0,7.5,1.0,15.122016,1.016064,...,float division by zero (MDEC-44),float division by zero (MDEO-11),0.2,float division by zero (MDEO-22),float division by zero (MDEN-11),float division by zero (MDEN-12),float division by zero (MDEN-13),float division by zero (MDEN-22),float division by zero (MDEN-23),float division by zero (MDEN-33)
5,0.0,0.0,1.0,1.0,2.096774,1.0,4.741935,1.0,9.276136,1.016064,...,float division by zero (MDEC-44),float division by zero (MDEO-11),0.2,float division by zero (MDEO-22),float division by zero (MDEN-11),float division by zero (MDEN-12),float division by zero (MDEN-13),float division by zero (MDEN-22),float division by zero (MDEN-23),float division by zero (MDEN-33)
10,0.0,invalid value encountered in double_scalars (A...,1.0,invalid value encountered in double_scalars (A...,1.0,invalid value encountered in double_scalars (A...,1.0,invalid value encountered in double_scalars (A...,1.016064,invalid value encountered in double_scalars (A...,...,float division by zero (MDEC-44),float division by zero (MDEO-11),0.333333,float division by zero (MDEO-22),float division by zero (MDEN-11),float division by zero (MDEN-12),float division by zero (MDEN-13),float division by zero (MDEN-22),float division by zero (MDEN-23),float division by zero (MDEN-33)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3875,0.0,invalid value encountered in double_scalars (A...,1.0,invalid value encountered in double_scalars (A...,1.0,invalid value encountered in double_scalars (A...,1.0,invalid value encountered in double_scalars (A...,1.016064,invalid value encountered in double_scalars (A...,...,float division by zero (MDEC-44),float division by zero (MDEO-11),float division by zero (MDEO-12),float division by zero (MDEO-22),float division by zero (MDEN-11),float division by zero (MDEN-12),float division by zero (MDEN-13),float division by zero (MDEN-22),float division by zero (MDEN-23),float division by zero (MDEN-33)
3876,0.0,0.0,1.0,1.0,3.5,1.0,5.8125,1.0,11.534985,1.016064,...,float division by zero (MDEC-44),0.25,0.4,float division by zero (MDEO-22),float division by zero (MDEN-11),float division by zero (MDEN-12),float division by zero (MDEN-13),float division by zero (MDEN-22),float division by zero (MDEN-23),float division by zero (MDEN-33)
3878,1.59375,0.45,1.96875,1.6,2.552083,1.85,9.9375,5.35,31.731983,13.924974,...,float division by zero (MDEC-44),0.25,float division by zero (MDEO-12),float division by zero (MDEO-22),float division by zero (MDEN-11),float division by zero (MDEN-12),float division by zero (MDEN-13),float division by zero (MDEN-22),float division by zero (MDEN-23),float division by zero (MDEN-33)
3889,0.56,0.333333,1.56,1.466667,2.206667,2.566667,7.04,6.4,20.480828,18.731656,...,float division by zero (MDEC-44),float division by zero (MDEO-11),0.2,float division by zero (MDEO-22),float division by zero (MDEN-11),float division by zero (MDEN-12),float division by zero (MDEN-13),float division by zero (MDEN-22),float division by zero (MDEN-23),float division by zero (MDEN-33)
3890,0.0,0.0,1.0,1.0,2.692308,1.0,5.307692,1.0,10.475291,1.016064,...,float division by zero (MDEC-44),float division by zero (MDEO-11),0.516398,0.25,float division by zero (MDEN-11),float division by zero (MDEN-12),float division by zero (MDEN-13),float division by zero (MDEN-22),float division by zero (MDEN-23),float division by zero (MDEN-33)

In [19]:
df_error.shape

(74, 281)

In [20]:
df1.drop(columns="ROMol", inplace=True)
df1.columns

Index(['SMILES', 'InChI', 'InChIKey', 'K3FeCN6'], dtype='object')

In [21]:
df3 = pd.merge(df1, df2, left_index=True, right_index=True)
df3

,SMILES,InChI,InChIKey,K3FeCN6,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,CC(C)(C)c1ccc(O)c(C(C)(C)C)c1,"InChI=1S/C14H22O/c1-13(2,3)10-7-8-12(15)11(9-1...",ICKWICRCANNIBI-UHFFFAOYSA-N,1,11.505844,10.846846,0,0,16.340176,2.416610,...,9.745136,47.504739,206.167065,5.572083,342,22,78.0,88.0,8.208333,3.027778
1,C=CCc1ccc(O)c(OC)c1,InChI=1S/C10H12O2/c1-3-4-8-5-6-9(11)10(7-8)12-...,RRAFCDWBNXTKKO-UHFFFAOYSA-N,1,8.554231,8.109401,0,0,14.962536,2.287941,...,9.038959,42.028335,164.083730,6.836822,204,15,54.0,60.0,4.833333,2.944444
3,COc1ccc(O)cc1,"InChI=1S/C7H8O2/c1-9-7-4-2-6(8)3-5-7/h2-5,8H,1H3",NWVVVBRKAWDGAB-UHFFFAOYSA-N,1,6.473351,6.127583,0,0,11.189957,2.193993,...,8.590258,37.289972,124.052429,7.297202,90,9,40.0,43.0,3.472222,2.166667
5,COc1ccc(O)c(C(C)(C)C)c1,"InChI=1S/C11H16O2/c1-11(2,3)9-7-8(13-4)5-6-10(...",MRBKEAMVRSLQPH-UHFFFAOYSA-N,1,9.676484,9.250172,0,0,15.001092,2.375265,...,9.449908,44.334127,180.115030,6.210863,234,18,64.0,72.0,6.395833,2.861111
10,COc1cc(C)ccc1O,"InChI=1S/C8H10O2/c1-6-3-4-7(9)8(5-6)10-2/h3-5,...",PETRWTHZSKVLRE-UHFFFAOYSA-N,1,7.249407,6.999636,0,0,12.376804,2.268236,...,8.913416,39.312189,138.068080,6.903404,115,12,46.0,51.0,4.333333,2.361111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3875,CC(C)(C)c1cccc(O)c1,"InChI=1S/C10H14O/c1-10(2,3)8-5-4-6-9(11)7-8/h4...",CYEKUDPFXBLGHH-UHFFFAOYSA-N,-1,8.302711,7.854212,0,0,12.507813,2.317687,...,9.193499,41.341650,150.104465,6.004179,148,13,54.0,59.0,5.284722,2.333333
3876,COc1ccc(O)c(C(C)=O)c1,InChI=1S/C9H10O3/c1-6(10)8-5-7(12-2)3-4-9(8)11...,MLIBGOFSXXWRIY-UHFFFAOYSA-N,1,8.732571,8.385662,0,0,14.410869,2.316847,...,9.166911,42.386933,166.062994,7.548318,193,16,56.0,63.0,5.444444,2.805556
3878,O=C(c1ccccc1)c1ccccc1O,InChI=1S/C13H10O2/c14-12-9-5-4-8-11(12)13(15)1...,HJIAMFHSAAEUKR-UHFFFAOYSA-N,-1,11.411168,9.996080,0,0,19.589763,2.345288,...,9.458216,46.802797,198.068080,7.922723,362,21,74.0,85.0,4.694444,3.416667
3889,CCCOc1ccc(O)cc1,InChI=1S/C9H12O2/c1-2-7-11-9-5-3-8(10)4-6-9/h3...,KIIIPQXXLVCCQP-UHFFFAOYSA-N,1,7.887564,7.185473,0,0,13.725227,2.205946,...,8.696677,40.025593,152.083730,6.612336,174,11,48.0,51.0,3.972222,2.666667
3890,COc1ccc(O)c(OC)c1,InChI=1S/C8H10O3/c1-10-6-3-4-7(9)8(5-6)11-2/h3...,MNVMYTVDDOXZLS-UHFFFAOYSA-N,1,7.847124,7.585047,0,0,13.665822,2.283101,...,8.997518,40.726374,154.062994,7.336333,154,14,50.0,56.0,4.583333,2.694444

In [22]:
df3.shape

(74, 1336)

In [23]:
df3.dropna(axis=1, inplace=True)
df3.shape

(74, 1336)

In [24]:
df3.to_csv("mordred.csv", index=False)